apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-nginx-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
spec:
  rules:
    - host: anunciosapp.ml 
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: {{ .Values.anunciosAppBackend.serviceName }}
              servicePort: 80
          - path: /?(.*)
            backend:
              serviceName: {{ .Values.anunciosAppFrontend.serviceName }}
              servicePort: 80
    